# Generated by Django 3.2 on 2024-12-01 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('employee', models.CharField(blank=True, max_length=255, null=True)),
                ('customer', models.CharField(blank=True, max_length=255, null=True)),
                ('complete_expect', models.DateTimeField(blank=True, null=True)),
                ('color', models.CharField(default='#0D6EFD', max_length=10)),
                ('quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('size', models.CharField(blank=True, max_length=10, null=True)),
                ('note', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
