# Generated by Django 3.2 on 2024-12-01 18:01

from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='code',
            field=models.CharField(default=home.models.generate_order_code, max_length=10, unique=True),
        ),
    ]
