# Generated by Django 3.2 on 2024-12-02 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_order_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='imgage',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
