# Generated by Django 3.2 on 2024-12-03 12:36

from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_order_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='code',
            field=models.CharField(default=home.models.generate_order_code, max_length=10),
        ),
    ]
